// This file is auto generated by TypescriptableLaravel.
const Routes: Record<App.Route.Name, App.Route.Link> = {
  'sanctum.csrf-cookie': {
    name: 'sanctum.csrf-cookie',
    path: '/sanctum/csrf-cookie',
    params: undefined,
    methods: ['GET'],
  },
  'api/user': {
    name: 'api/user',
    path: '/api/user',
    params: undefined,
    methods: ['GET'],
  },
  '/': {
    name: '/',
    path: '/',
    params: undefined,
    methods: ['GET'],
  },
}

declare global {
  interface Window {
    Routes: Record<App.Route.Name, App.Route.Link>
  }
}

if (typeof window !== 'undefined') {
  if (typeof window !== undefined && typeof window.Routes !== undefined)
    window.Routes = Routes
}

export { Routes }
