// This file is auto generated by TypescriptableLaravel.
declare namespace App.Route {
  export type Name = '/' | 'api/user' | 'sanctum.csrf-cookie';
  export type Path = '/' | '/api/user' | '/sanctum/csrf-cookie';
  export type Params = {
    'sanctum.csrf-cookie': never,
    'api/user': never,
    '/': never
  };

  export type Method = 'HEAD' | 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  export type ParamType = string | number | boolean | undefined;
  export interface Link { name: App.Route.Name; path: App.Route.Path; params?: App.Route.Params[App.Route.Name],  methods: App.Route.Method[]; }
  export type RouteConfig<T extends App.Route.Name> = {
    name: T;
    params?: T extends keyof App.Route.Params ? App.Route.Params[T] : never;
  };
}